name: racedetector
on:
  pull_request:
  push:
    branches:
      - "main"

jobs:
  coverage:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version-file: "go.mod"

      - uses: actions/checkout@v3

      - run: go test -race .
